require 'facets/hash/symbolize_keys'
require 'facets/kernel/not_nil'
require 'facets/module/attr_class_accessor'
require 'facets/module/attr_setter'
require 'facets/numeric/positive'
require 'facets/symbol/variablize'
