require_relative 'core_components/configuration/raise_error'
require_relative 'core_components/configuration/configuration_factory'
require_relative 'core_components/configuration/item_factory'
require_relative 'core_components/configuration/setup'

require_relative 'core_components/register_map/generic_map'
require_relative 'core_components/register_map/loader'
require_relative 'core_components/register_map/component'
require_relative 'core_components/register_map/item'
require_relative 'core_components/register_map/register_map_factory'
require_relative 'core_components/register_map/register_block_factory'
require_relative 'core_components/register_map/register_factory'
require_relative 'core_components/register_map/bit_field_factory'
require_relative 'core_components/register_map/item_factory'
require_relative 'core_components/register_map/setup'

require_relative 'core_components/rtl/identifier'
require_relative 'core_components/rtl/signal_declaration'
require_relative 'core_components/rtl/port_declaration'
require_relative 'core_components/rtl/parameter_declaration'
require_relative 'core_components/rtl/register_index'
require_relative 'core_components/rtl/component'
require_relative 'core_components/rtl/item'
require_relative 'core_components/rtl/setup'
