enable :global        , [:data_width, :address_width]
enable :register_block, [:name, :byte_size]
enable :register      , [:offset_address, :name, :array, :shadow, :accessibility, :uniquness_validator]
enable :bit_field     , [:bit_assignment, :name, :type, :initial_value, :reference]
enable :bit_field     , :type, [:rw, :ro, :reserved]
enable :register_block, [:module_definition, :clock_reset, :host_if, :response_mux]
enable :register_block, :host_if, [:apb, :axi4lite]
enable :register      , [:address_decoder, :read_data]
enable :register_block, [:ral_package_definition, :block_model_definition, :reg_model_declarations, :block_model_constructor, :reg_model_creator, :block_model_default_map_creator]
enable :register      , [:reg_model_definition, :field_model_declarations, :reg_model_constructor, :field_model_creator, :shadow_index_configurator, :reg_model_declaration, :reg_model_creation]
enable :bit_field     , [:field_model_declaration, :field_model_creation]
