enable :global        , [:data_width, :address_width]
enable :register_block, [:name, :byte_size]
enable :register      , [:offset_address, :name, :array, :shadow, :external, :accessibility, :uniquness_validator]
enable :bit_field     , [:bit_assignment, :name, :type, :initial_value, :reference]
enable :bit_field     , :type, [:rw, :ro, :reserved]
enable :register_block, [:top_module, :clock_reset, :host_if, :response_mux]
enable :register_block, :host_if, [:apb, :axi4lite]
enable :register      , [:address_decoder, :read_data, :bus_exporter]
enable :register_block, [:ral_package, :block_model, :constructor, :sub_model_creator, :default_map_creator]
enable :register      , [:reg_model, :constructor, :field_model_creator, :shadow_index_configurator, :sub_block_model]
enable :bit_field     , :field_model
